name: Java CD with Ant

on:
  workflow_dispatch:

jobs:

  dist:
    runs-on: ubuntu-latest

    inputs:
      version:
        description: Version of Dependency Finder to build
        required: true

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate distribution artifacts
        run: ant -Drelease=${{ inputs.homedrive }} dist

      - name: Store distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ github.workspace }}/dist/*
