name: Release from Tag

on:
  push:
    tags:
      - "*.*.*"

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.head_commit.id }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate distribution artifacts
        run: ant -Drelease=${{ github.ref_name }} dist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Release ${{ github.ref_name }}
            
            Compiled with Java 17.
          files: dist/*

      - name: URL to new release
        run: echo "Dependency Finder [${{ github.ref_name }}](${{ steps.create_release.outputs.url }})" >> $GITHUB_STEP_SUMMARY
